const userPrompt = {
    choiceMenuPrompt: "What would you like to do?",
    emp_firstname: "What is the employee's first name?",
    emp_lastname: "What is the employee's last name?",
    emp_role: "What is the employee's role?",
    emp_manager: "Who is the employee's manager?",
    del_emp_firstname: "There are multiple employees with that name.  Select which one you'd like to delete below.",
    del_emp_lastname: "Are you sure you want to delete ",
    allDepartments: "What department would you like to view?",
    viewAllRole: "What role would you like to search?",
    roleUpdate: "Please select new role for the employee",
    newManager: "which manager would you like to be the new manager of employee?",
    searchByManager: "Choose the manager whose employee's you'd like to view?",
    newRole: "What role would you like to add?",
    deleteRole: "What role would you like to delete?",
    departmentDeleteRole: "Which department would you like to delete role from?",
    salary: "What salary will this role have?",
    department: "What department would you like to add a role into?",
    newDepartment: "What is the name of the department you'd like to add?",
    deleteDepartment: "What department would you like to delete?"
} 